routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PublicationController@index');
Route::resource('/publications', 'PublicationController')->only([
    'index', 'show'
]);

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::post('/publications/comments/{publication}', 'CommentController@store')->name('comments.store');
    Route::resource('/publications', 'PublicationController')->except([
        'index', 'show'
    ]);
});

app/Comment.php
<?php

namespace App;

use App\Publication;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['content', 'status', 'publication_id', 'user_id'];

    public function publication()
    {
        return $this->belongsTo(publication::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Publication.php
<?php

namespace App;

use App\Comment;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Publication extends Model
{
    protected $fillable = ['title', 'content'];

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function isCommentedBy(User $user)
    {
        return $this->comments->where('user_id', $user->id)->count() > 0;
    }
}

app/User.php
<?php

namespace App;

use App\Publication;
use App\Comment;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function publications()
    {
        return $this->hasMany(Publication::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Publication;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function store(Request $request, Publication $publication)
    {
        $comment = auth()->user()->comments()->create([
            'content' => $request->content,
            'publication_id' => $publication->id,
            'status' => 'APROBADO',
        ]);

        $data = [
            'user' => auth()->user()->name,
            'comment' => $comment->content,
            'publication' => $publication->title,
            'publication_url' => route('publications.show', $publication),
        ];

        \Mail::send('emails.comment', $data, function ($message) {

            $message->from('rorepoid@example.com', 'rorepoid');

            $message->to('user@example.com')->subject('Notificación');

        });


        return redirect()->route('publications.show', $publication);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PublicationController.php
<?php

namespace App\Http\Controllers;

use App\Publication;
use Illuminate\Http\Request;

class PublicationController extends Controller
{
    public function index()
    {
        return view('publications.index', ['publications' => Publication::orderBy('updated_at', 'desc')->paginate(10)]);
    }

    public function create()
    {
        return view('publications.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string',
        ]);

        auth()->user()->publications()->create($validatedData);

        return redirect()->action('PublicationController@index');
    }

    public function show(Publication $publication)
    {
        return view('publications.show', compact('publication'));
    }

    public function edit(Publication $publication)
    {
        return view('publications.edit', compact('publication'));
    }

    public function update(Request $request, Publication $publication)
    {
        $validatedData = $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string',
        ]);

        $publication->update($validatedData);

        return redirect()->action('PublicationController@index');
    }

    public function destroy(Publication $publication)
    {
        $publication->delete();

        return redirect()->action('PublicationController@index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a class="navbar-brand user-select-none" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        @auth
                            <li class="nav-item active mr-4">
                                <a class="nav-link user-select-none" href="{{ route('publications.create') }}">Nueva Publicación</a>
                            </li>
                        @endauth
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item active">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item active">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item active dropdown">
                                <a id="navbarDropdown" class="nav-link user-select-none dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right bg-dark" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item-text text-white user-select-none text-decoration-none" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main style="background-color: #e2e8f0;" class="py-4 min-vh-100">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/publications/create.blade.php
@extends('layouts.app')

@section('content')
    <div role="main" class="container">
        <h1 class="mt-5">Crear nueva publicación</h1>
        <form action="{{ route('publications.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <label for="title">Título</label>
                <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" id="title" aria-describedby="title" placeholder="Enter title">
            </div>
            <div class="form-group">
                <label for="content">Contenido</label>
                <textarea type="content" name="content" class="form-control @error('content') is-invalid @enderror" id="content" placeholder="Enter the content" rows="15"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
@endsection

resources/views/publications/edit.blade.php
@extends('layouts.app')

@section('content')
    <div role="main" class="container">
        <h1 class="mt-5">Editar Publicación</h1>
        <form action="{{ route('publications.update', $publication) }}" method="POST">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="title">Título</label>
                <input type="text" name="title" value="{{ $publication->title }}" class="form-control @error('title') is-invalid @enderror" id="title" aria-describedby="title" placeholder="Enter title">
            </div>
            <div class="form-group">
                <label for="content">Contenido</label>
                <textarea type="content" name="content" class="form-control @error('content') is-invalid @enderror" id="content" placeholder="Enter the content" rows="15"
                >{{ $publication->content }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
@endsection

resources/views/publications/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2 class="mt-4">Blog</h2>
    <hr>
    <div class="row d-flex flex-column justify-content-center align-items-center">
        {{ $publications->links() }}

        <div class="col-12 col-lg-9 mb-5">
            @forelse($publications as $publication)
                <div class="row mb-5 card card-body rounded-lg border border-dark shadow">
                    <div class="col-12">
                        <a href="{{ route('publications.show', $publication) }}" class="text-dark text-decoration-none"><h1>{{ $publication->title }}</h1></a>
                        <span class="badge text-secondary text-uppercase user-select-none">
                            {{ $publication->user->name }} - {{ \Carbon\Carbon::createFromTimeStamp(strtotime($publication->updated_at))->diffForHumans() }}
                        </span>
                        <div class="text-break mt-3 ml-1">
                            <p style="display: -webkit-box; -webkit-line-clamp: 4; -webkit-box-orient: vertical; overflow: hidden; text-overflow: ellipsis;"
                            >{{ $publication->title }}
                            </p>
                        </div>

                        <div class="d-flex ml-1">
                            <a href="{{ route('publications.show', $publication) }}" class="btn btn-outline-dark btn-sm mr-4">Leer artículo completo</a>
                            @auth
                                @if($publication->user->id == auth()->user()->id)
                                    <a href="{{ route('publications.edit', $publication) }}" class="btn btn-outline-success btn-sm mr-4">Editar</a>
                                    <form action="{{ route('publications.destroy', $publication) }}" method="POST">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                                    </form>
                                @endif
                            @endauth
                        </div>
                    </div>
                </div>

            @empty
                <h1>Aún no hay publicaciones</h1>
            @endforelse
        </div>

        {{ $publications->links() }}
    </div>
</div>
@endsection

resources/views/publications/show.blade.php
@extends('layouts.app')

@section('content')
    <main role="main" class="container bg-white rounded-lg px-lg-5">
        <h1 class="font-weight-bold py-3">{{ $publication->title }}</h1>
        <p>Posted by <span class="text-primary">{{ $publication->user->name }}</span>
            - {{ \Carbon\Carbon::createFromTimeStamp(strtotime($publication->updated_at))->diffForHumans() }}</p>
        <p class="h4">{{ $publication->content }}</p>
        @auth
            @if(!$publication->isCommentedBy(auth()->user()))
                <form action="{{ route('comments.store', $publication) }}" method="POST">
                    @csrf
                    <div class="form-group mt-3">
                        <div class="input-group mb-3">
                            <input type="text" name="content" class="form-control @error('content') is-invalid @enderror"
                                   id="content" placeholder="Submit your Comment" rows="5">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">Comentario</button>
                            </div>
                        </div>
                    </div>
                </form>
            @endif
        @endauth
        @forelse($publication->comments as $comment)
            <div class="card mt-4">
                <div class="card">
                    <div class="card-header">
                        <h4>Discussion</h4>
                    </div>
                </div>
                <div class="bg-white rounded-lg border-secondary p-3">
                    <h5 class="card-title">{{ $comment->user->name }}</h5>
                    <p class="text-secondary h5">{{ $comment->content }}</p>
                </div>
            </div>
        @empty
            <div class="card">
                <div class="card-header">
                    <h4>Be the first to comment</h4>
                </div>
            </div>
        @endforelse
    </main>
@endsection